# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_identi_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNum', models.CharField(default='', max_length=32)),
                ('identiCode', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
