# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaProgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradDetail',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('compay', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=32)),
                ('specialty', models.CharField(max_length=32)),
                ('grad_weixin_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='grad_weixin_id',
            field=models.CharField(default='aaa', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='grad_weixin_id',
            field=models.CharField(default='ww', max_length=32),
            preserve_default=False,
        ),
    ]
