# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaProgram', '0002_auto_20170826_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asker_openid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='answer',
            name='grad_weixin_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='graddetail',
            name='compay',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='graddetail',
            name='grad_weixin_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='graddetail',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='graddetail',
            name='school',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='graddetail',
            name='specialty',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
