# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaProgram', '0003_auto_20170826_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graddetail',
            old_name='compay',
            new_name='company',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graddetail',
            name='avatar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='ask_time',
            field=models.IntegerField(default=0),
        ),
    ]
