# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaProgram', '0004_auto_20170826_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='graddetail',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qaProgram.Picture'),
        ),
    ]
