# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaProgram', '0007_auto_20170826_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='qid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
