# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaProgram', '0008_auto_20170826_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-answer_time']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-ask_time']},
        ),
    ]
