# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eec_alumni',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=32)),
                ('major', models.CharField(max_length=32)),
                ('brief_intro', models.TextField()),
                ('intro', models.TextField()),
                ('degree', models.CharField(max_length=32)),
                ('interview_info', models.TextField()),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smallProgram.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Push_position',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('info', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('publish_time', models.TimeField()),
                ('keywords', models.CharField(max_length=32)),
                ('requirement', models.TextField()),
                ('pluses', models.TextField()),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smallProgram.Company')),
            ],
        ),
    ]
