# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallProgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='push_position',
            name='publish_time',
        ),
    ]
