# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smallProgram', '0002_remove_push_position_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='push_position',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
